# Generated by Django 4.2 on 2023-09-23 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("isActive", models.BooleanField(default=True)),
                (
                    "survey_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("survey_title", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("detail", models.TextField()),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("choice", "Option"),
                            ("check", "Check Box"),
                            ("image", "Image"),
                            ("file", "File"),
                        ],
                        max_length=20,
                    ),
                ),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("choices", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        default="master",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Surveys", "ordering": ("-date_created",),},
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("data", models.TextField(max_length=400)),
                (
                    "survey_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.survey"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Answers", "ordering": ("-date",),},
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                ("required", models.BooleanField(verbose_name="Required")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "text (multiple line)"),
                            ("short-text", "short text (one line)"),
                            ("radio", "radio"),
                            ("select", "select"),
                            ("select-multiple", "Select Multiple"),
                            ("select_image", "Select Image"),
                            ("integer", "integer"),
                            ("float", "float"),
                            ("date", "date"),
                        ],
                        default="text",
                        max_length=200,
                        verbose_name="Type",
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="The choices field is only used if the question type\n      is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .",
                        null=True,
                        verbose_name="Choices",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.survey",
                        verbose_name="Survey",
                    ),
                ),
            ],
            options={"verbose_name": "question", "verbose_name_plural": "questions",},
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Update date"),
                ),
                (
                    "body",
                    models.TextField(blank=True, null=True, verbose_name="Content"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.surveyresponse",
                        verbose_name="Response",
                    ),
                ),
            ],
        ),
    ]
