# Generated by Django 4.2 on 2023-09-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_surveyresponse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="time_created",
            field=models.TimeField(auto_now=True),
        ),
    ]
